version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - todo-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - todo-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongo-data: